name: droneenv
description: Droneenv Flutter App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_native_splash: ^0.1.9
  provider: ^3.0.0
  material_design_icons_flutter: ^4.0.5755
  community_material_icon: ^5.4.55

flutter_native_splash:
  image: assets/images/splash.png
  color: "141414"
  fill: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  fonts:
    - family: Jockey
      fonts:
        - asset: assets/fonts/JockeyOne-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Vampiro
      fonts:
        - asset: assets/fonts/VampiroOne-Regular.ttf
    - family: Blinker
      fonts:
        - asset: assets/fonts/Blinker-SemiBold.ttf



  uses-material-design: true

  assets:
    - assets/images/logo-dark.png
    - assets/images/logo-light.png


